In [1]:
import sys
import os

import streamlit as st
from core.utils import Sermon, Person, get_short_info
from collections import Counter

import plotly.express as px
from plotly.subplots import make_subplots
import networkx as nx

import plotly.graph_objects as go
import pandas as pd

import json
import re

from rapidfuzz import fuzz

In [2]:
def flatten(xss):
    return [x for xs in xss for x in xs]

In [3]:
def create_quote_dist_chart(ids: list, type: str, searchkey: str="") -> go.Figure:
    type_dict = {
        "orgelpredigt": "Orgelpredigtzitate",
        "musikwerk": "Liedzitate",
        "quelle": "Literaturzitate",
    }
    if type not in type_dict.keys():
        occ_fig = go.Figure()
        occ_fig.update_layout(title_text="Type not recognised!")
        return occ_fig
    
    else:
        chunked_text = [0]*100
        thumbnails = [""]*100

        for id in ids:
            sermon = Sermon(id)

            dec = int(len(sermon.words) / 99)
            overhang = len(sermon.words) % dec

            for i, j in zip(range(0, len(sermon.words), dec), range(0, 100)):
                if searchkey != "":
                    keys_unique = sermon.reference[i:i+dec]
                    keys_str = " ".join(flatten(keys_unique))
                    if searchkey in keys_str:
                        hit_test = 1
                        hit = f"{sermon.kurztitel}"
                    else:
                        hit_test = 0
                        hit = ""
                else:
                    types_unique = list(set(sermon.word_types[i:i+dec]))
                    types_str = " ".join([x for x in types_unique if isinstance(x, str)])
                    if type in types_str:
                        hit_test = 1
                        hit = f"{sermon.kurztitel}<br>"
                    else:
                        hit_test = 0
                        hit = ""
                
                chunked_text[j] = chunked_text[j] + hit_test
                thumbnails[j] = thumbnails[j] + hit
            if searchkey != "":
                last_keys_unique = sermon.reference[-overhang:]
                last_keys_str = " ".join(flatten(last_keys_unique))
                if searchkey in last_keys_str:
                    last_hit_test = 1
                    last_hit = f"{sermon.kurztitel}<br>"
                else:
                    last_hit_test = 0
                    last_hit = ""
            else:
                last_types_unique = list(set(sermon.word_types[-overhang:]))
                last_types_str = " ".join([x for x in last_types_unique if isinstance(x, str)])
                if type in last_types_str:
                    last_hit_test = 1
                    last_hit = f"{sermon.kurztitel}<br>"
                else:
                    last_hit_test = 0
                    last_hit = ""
            
            #chunked_text[-1] = chunked_text[-1] + last_orgelpredigt_test
            #thumbnails[-1] = thumbnails[-1] + last_hit

        occ_fig = go.Figure()

        for i in range(0, len(chunked_text)):
            hovertext = f'{chunked_text[i]} {type_dict[type]} im {i+1}%'
            if thumbnails[i] != "":
                    hovertext += f"<br>{thumbnails[i]}"

            gradient = chunked_text[i] * 15
            color = f'rgb({max(250-gradient, 0)},{max(250-gradient, 0)},{max(250-gradient, 0)})'
            occ_fig.add_trace(go.Bar(
                x = [f"{type_dict[type]} je Predigtprozent"],
                y = [100],
                marker_color = color,
                hovertext = hovertext
            ))

        occ_fig.update_layout(width=1500,height=500, showlegend=False)
        print(hit)
        return occ_fig

def group_sermons_in_years(data, interval: int) -> list:
    chunked_sermons = []
    start_year = 1600
    end_year = 1800
    yearfinder = re.compile(r'[0-9]{4}')
    for i in range(start_year, end_year, interval):
        sermons = []
        for id, info in data.items():
            year = int(re.findall(yearfinder, info['year'])[0])
            if year > i and year < i + interval:
                sermons.append(id)
        chunked_sermons.append(sermons)

    return chunked_sermons

In [4]:
# Get the list of all files in a directory
with open("predigten_übersicht.json", "r", encoding="utf-8") as file: 
    data = json.load(file)

# Ensure all entries have a 'year' key
cleaned = {k: v for k, v in data.items() if 'year' in v}

year_finder = re.compile(r'[0-9]{4}')

for k, v in data.items():
    year = re.findall(year_finder, v['year'])[0]
    if year:
        v['year'] = year
    else:
        v['year'] = '[s.a.]'

# Convert to nested list and sort by year
relevant_sermons = sorted(
    [[key, value['title'], int(value['year'])] for key, value in cleaned.items()],
    key=lambda x: x[2]
)

ids = [i[0] for i in relevant_sermons]

In [5]:
praetorius = "E080223"
in_dulci = "E100017"
dieterich = "E000003"

In [6]:
quote_time_dist = "gesamter_zeitraum"
quote_type = "orgelpredigt"
searchkey = in_dulci

In [7]:
if quote_time_dist == "50-Jahr-Intervalle":
    sermons_grouped_50 = group_sermons_in_years(data, 50)
    figs_50 = []
    for i in range(len(sermons_grouped_50)):
        figs_50.append(create_quote_dist_chart(sermons_grouped_50[i], quote_type,searchkey=searchkey))
    
    # Create subplots
    fig = make_subplots(rows=len(figs_50), 
                        cols=1, 
                        subplot_titles=[f"Verteilung in Predigten zwischen {1600 + (i*50)} und {1600+(i*50)+50} ({len(sermons_grouped_50[i])} Predigten)" for i in range(len(figs_50))])

    # Add traces from each figure to the subplots
    for i, fig_item in enumerate(figs_50):
        for trace in fig_item.data:
            fig.add_trace(trace, row=i+1, col=1)

    # Update layout
    fig.update_layout(height=1200, width=1000, showlegend = False)
    fig.update_layout(title_text="Accumulierte Verteilung von Zitaten in 50-Jahr Intervallen")

elif quote_time_dist == "25-Jahr-Intervalle":
    sermons_grouped_25 = group_sermons_in_years(data, 25)
    figs_25 = []
    for i in range(len(sermons_grouped_25)):
        figs_25.append(create_quote_dist_chart(sermons_grouped_25[i], quote_type,searchkey=searchkey))
    
    # Create subplots
    fig = make_subplots(rows=len(figs_25), 
                        cols=1, 
                        subplot_titles=[f"Verteilung in Predigten zwischen {1600 + (i*25)} und {1600+(i*25)+25} ({len(sermons_grouped_25[i])} Predigten)" for i in range(len(figs_25))])

    # Add traces from each figure to the subplots
    for i, fig_item in enumerate(figs_25):
        for trace in fig_item.data:
            fig.add_trace(trace, row=i+1, col=1)

    # Update layout
    fig.update_layout(height=1200, width=1000, showlegend = False)
    fig.update_layout(title_text="Accumulierte Verteilung von Zitaten in 25-Jahr Intervallen")

else:
    fig = create_quote_dist_chart(ids, quote_type, searchkey=searchkey)

fig.show()

In [8]:
sermon = Sermon("E000036")
quoted_item = "E100022"
passages = []
for i in range(len(sermon.chunked)):
    for j in range(len(sermon.chunked[i])):
        words = sermon.chunked[i][j]["words"]
        types = sermon.chunked[i][j]["types"]
        refs = sermon.chunked[i][j]["references"]
        test_refs = []
        for nr, ref in enumerate(refs):
            if quoted_item in ref:
                test_refs.append(nr)
        if len(test_refs):
            passages.append(" ".join(words))

In [9]:
passages

['zwingt die säiten in cithara,',
 'und laßt die süsse musica gantz freudenreich erschallen,',
 'daß ich möge mit jesulein,',
 'dem wunderschönen bräutgam mein,',
 'jn steter liebe wallen.',
 'singet, springet, jubiliret, triumphiret,',
 'danckt dem herren, groß ist der könig der ehren!',
 'singet, springet, jubiliret, triumphiret,',
 'danckt dem herren, groß ist der könig der ehren.']

In [10]:
def get_quoted_passages(quoted_item: str, ids: list):
    # get passages from quoted item in every sermon
    passages = []
    for id in ids:
        sermon = Sermon(id)
        for i in range(len(sermon.chunked)):
            for j in range(len(sermon.chunked[i])):
                words = sermon.chunked[i][j]["words"]
                types = sermon.chunked[i][j]["types"]
                refs = sermon.chunked[i][j]["references"]
                test_refs = []
                for nr, ref in enumerate(refs):
                    if quoted_item in ref:
                        test_refs.append(nr)
                if len(test_refs):
                    if j > 0:
                        words_before = " ".join(sermon.chunked[i][j-1]["words"])
                    else:
                        words_before = " ".join(sermon.chunked[i-1][-1]["words"])
                    if j < len(sermon.chunked[i])-1:
                        words_after = " ".join(sermon.chunked[i][j+1]["words"])
                    else:
                        words_after = " ".join(sermon.chunked[i+1][0]["words"])
                    passages.append([id, " ".join(words), words_before, words_after])
    
    return passages

passages = get_quoted_passages("E100022", ids)

In [12]:
results = pd.DataFrame(passages, columns=['sermon', 'verse', 'text_before', 'text_after'])

In [13]:
liedtext_morgenstern = [
"Wie schön leuchtet der Morgenstern /",
"Voll Gnad vnd Warheit von dem HERRN /",
"Die süsse Wurtzel Jesse?",
"Du Sohn Dauid auß Jacobs Stamm /",
"Mein König vnd mein Bräutigam /",
"Hast mir mein Hertz besessen /",
"Lieblich freundtlich Schön vnd herrlich /",
"Groß vnd ehrlich Reich von Gaben /",
"Hoch vnd sehr prächtig erhaben.",
"Ey mein Perle / du werthe Kron /",
"Wahr Gottes vnd Marien Sohn /",
"Ein hochgeborner König /",
"Mein Hertz heißt dich ein lilium,",
"Dein süsses Euangelium,",
"Jst lauter Milch vnd Honig /",
"Ey mein Blümlein Hosianna /",
"Himmlisch Manna Das wir essen /",
"Deiner kan ich nicht vergessen.",
"Geuß sehr tieff in mein Hertz hineyn /",
"Du heller Jaspis vnd Rubin /",
"Die Flamme deiner Liebe.",
"Vnd erfreuw mich / daß ich doch bleib",
"An deinem außerwehlten Leib",
"Ein lebendige Rippe /",
"Nach dir ist mir /",
"Gratiosa cœli rosa Kranck vnd glümmet",
"Mein Hertz / durch Liebe verwundet.",
"Von Gott kompt mir ein Frewdenschein /",
"Wenn du mit deinen Eugelein /",
"Mich freundtlich thust anblicken /",
"O HERR Jesu mein trawtes Gut /",
"Dein Wort / dein Geist / dein Leib vnd Blut /",
"Mich innerlich erquicken. Nimm mich /",
"freundtlich Jn dein Arme /",
"Daß ich warme Werd von Gnaden /",
"Auff dein Wort komm ich geladen.",
"HERR Gott Vatter / mein starcker Heldt /",
"Du hast mich ewig / für der Welt /",
"In deinem Sohn geliebet /",
"Dein Sohn hat mich jhm selbst vertrawt /",
"Er ist mein Schatz / ich bin sein Braut /",
"Sehr hoch in jhm erfreuwet.",
"Eya Eya Himmlisch Leben /",
"wirdt er geben Mir dort oben /",
"Ewig soll mein Hertz jhn loben.",
"Zwingt die Sayten in Cythara.",
"Vnd laßt die süsse Musica,",
"Gantz frewdenreich erschallen:",
"Daß ich möge mit Jesulein /",
"Dem wunder schönen Bräutgam mein /",
"In stäter Liebe wallen.",
"Singet springet Jubilieret triumphieret /",
"Danckt dem HERREN Groß ist der König der Ehren.",
"Wie bin ich doch so hertzlich fro /",
"Daß mein Schatz ist das A vnd O /",
"Der Anfang / vnd das Ende:",
"Er wirdt mich doch zu seinem Preyß /",
"Auffnemmen in das Paradeiß /",
"Deß klopff ich in die Hände.",
"Amen Amen Komm du schone",
"FrewdenKrone Bleib du nicht lange /",
"Deiner wart ich mit Verlangen."
]

In [14]:
results

,sermon,verse,text_before,text_after
0,E000091,ey/ mein perle du werthe cron/,was ich gesucht bin ich gewehrt.,wahr gottes und marien sohn/
1,E000091,wahr gottes und marien sohn/,ey/ mein perle du werthe cron/,ein hochgeborner könig/ mein hertz heisst dich...
2,E000091,ein hochgeborner könig/ mein hertz heisst dich...,wahr gottes und marien sohn/,dein süsses evangelium/ ist lauter milch und h...
3,E000091,dein süsses evangelium/ ist lauter milch und h...,ein hochgeborner könig/ mein hertz heisst dich...,ey mein/ blümlein/ hosianna/
4,E000091,ey mein/ blümlein/ hosianna/,dein süsses evangelium/ ist lauter milch und h...,himlisch manna/ daß wir essen/
5,E000091,himlisch manna/ daß wir essen/,ey mein/ blümlein/ hosianna/,deiner kan ich nicht vergessen.
6,E000091,deiner kan ich nicht vergessen.,himlisch manna/ daß wir essen/,zwingt die seiten in cythara/
7,E000091,zwingt die seiten in cythara/,deiner kan ich nicht vergessen.,vnd lasst die süsse musica/
8,E000091,vnd lasst die süsse musica/,zwingt die seiten in cythara/,ganz freudenreich erschallen/ daß ich möge mit...
9,E000091,ganz freudenreich erschallen/ daß ich möge mit...,vnd lasst die süsse musica/,den allerhöchsten bräutgam mein/
10,E000091,den allerhöchsten bräutgam mein/,ganz freudenreich erschallen/ daß ich möge mit...,jn steter liebe wallen/
11,E000091,jn steter liebe wallen/,den allerhöchsten bräutgam mein/,singet/ springet/ jubiliret/ triumphiret/
12,E000091,singet/ springet/ jubiliret/ triumphiret/,jn steter liebe wallen/,danckt dem herrn/ groß ist der könig der ehren.
13,E000091,danckt dem herrn/ groß ist der könig der ehren.,singet/ springet/ jubiliret/ triumphiret/,vnd so viel vom ersten stück/
14,E000083,zwingt die saiten in cythara/,2. wem es vorgespielet worden?,und lasst die süsse musica gantz freudenreich ...
15,E000083,und lasst die süsse musica gantz freudenreich ...,zwingt die saiten in cythara/,singet/ springet/ jubiliret/ triumphiret/
16,E000083,singet/ springet/ jubiliret/ triumphiret/,und lasst die süsse musica gantz freudenreich ...,danckt dem herren/ groß ist der könig der ehren/
17,E000083,danckt dem herren/ groß ist der könig der ehren/,singet/ springet/ jubiliret/ triumphiret/,amen.
18,E000083,amen.,danckt dem herren/ groß ist der könig der ehren/,frolocket mit händen alle völcker/
19,E000079,zwingt die säiten in cithara/,sollen wir doch dem herrn singen und spielen i...,und last die süsse musica/
20,E000079,und last die süsse musica/,zwingt die säiten in cithara/,gantz freudenreich erschallen. müssen wir scho...
21,E000079,gantz freudenreich erschallen. müssen wir scho...,und last die süsse musica/,oder die harpfen an die weide hengen/
22,E000075,so zwingt demnach die saiten in cithara/,sonst ist all euer gottesdienst eitel und gieb...,und laßt die süße musica gantz freudenreich er...
23,E000075,und laßt die süße musica gantz freudenreich er...,so zwingt demnach die saiten in cithara/,singet/ klinget/ jubiliret/ triumphiret/
24,E000075,singet/ klinget/ jubiliret/ triumphiret/,und laßt die süße musica gantz freudenreich er...,danckt dem herren/ groß ist der könig der ehren!
25,E000075,danckt dem herren/ groß ist der könig der ehren!,singet/ klinget/ jubiliret/ triumphiret/,dir aber/ o du vater des liechts/
26,E000072,zwingt die saiten in cithara/,43/32. und die christliche kirche redet dort i...,und last die süße musica gantz n b freudenreic...
27,E000072,und last die süße musica gantz n b freudenreic...,zwingt die saiten in cithara/,so wird adam auff dem felde/
28,E000070,"so zwingt die säiten in cithara,",amen. demnach,und lasst die süsse musica gantz freudenreich ...
29,E000070,und lasst die süsse musica gantz freudenreich ...,"so zwingt die säiten in cithara,",singet/ klinget/ jubiliret/ triumphiret/
30,E000070,singet/ klinget/ jubiliret/ triumphiret/,und lasst die süsse musica gantz freudenreich ...,danckt dem herren/ groß ist der könig der ehren.
31,E000070,danckt dem herren/ groß ist der könig der ehren.,singet/ klinget/ jubiliret/ triumphiret/,si vox praeconis clara undique personat alto i...
32,E000068,"zwingt die seiten in cithara,",nun,zwingt die pfeiffen in organo und lasst die sü...
33,E000068,zwingt die pfeiffen in organo und lasst die sü...,"zwingt die seiten in cithara,",gantz freudenreich erschallen.
34,E000068,gantz freudenreich erschallen.,zwingt die pfeiffen in organo und lasst die sü...,alles/ was odem hat/
35,E000056,das eintzige gesäzz: zwingt die saiten in cith...,mit einander werden gesungen und geklungen haben/,der zu unserer orgel-weyhe erwehlte text/
36,E000104,zwingt doch die säyten in cithara/,und mit vollem munde ihn loben!,und last die schöne musica gantz freudenreich ...
37,E000104,und last die schöne musica gantz freudenreich ...,zwingt doch die säyten in cithara/,selbst die seraphinen gehen euch mit ihrem exe...
38,E000052,zwingt die säyten in cythara etc.,singet mit einstimmen unserer lobschallenden n...,und bethet darauf ein gläubiges und andächtige...
39,E000052,"zwingt die säyten in cithara,",amabimus &amp; laudabimus wir werden gott lieb...,und last die süsse musica gantz freudenreich e...
40,E000052,und last die süsse musica gantz freudenreich e...,"zwingt die säyten in cithara,",daß ich möge mit jesulein dem allerschönsten b...
41,E000052,daß ich möge mit jesulein dem allerschönsten b...,und last die süsse musica gantz freudenreich e...,"nimmermehr kan eine orgel so viel züge haben,"
42,E000061,herr gott vater mein starcker held etc.,wenn wir noch zuvor zur ermunterung unsrer and...,den 5. 6. und 7.
43,E000061,wie schön leuchtet der morgenstern.,v. aus dem liede:,das heutige heilige evangelium am 1.
44,E000042,"zwingt die saiten in cythara,","auch einander, also desto freudiger zuruffen.","und lasst die süsse musica,"
45,E000042,"und lasst die süsse musica,","zwingt die saiten in cythara,","ganz freudenreich erschallen, daß ich möge mit..."
46,E000042,"ganz freudenreich erschallen, daß ich möge mit...","und lasst die süsse musica,",jn steter liebe wallen!
47,E000042,jn steter liebe wallen!,"ganz freudenreich erschallen, daß ich möge mit...","singet, springet, jubiliret, triumphiret,"
48,E000042,"singet, springet, jubiliret, triumphiret,",jn steter liebe wallen!,"danckt dem herren, groß ist der könig der ehren."
49,E000042,"danckt dem herren, groß ist der könig der ehren.","singet, springet, jubiliret, triumphiret,",amen!
50,E000036,"zwingt die säiten in cithara,",mit eurer angenehmen music uns eine sabbathslu...,und laßt die süsse musica gantz freudenreich e...
51,E000036,und laßt die süsse musica gantz freudenreich e...,"zwingt die säiten in cithara,","daß ich möge mit jesulein,"
52,E000036,"daß ich möge mit jesulein,",und laßt die süsse musica gantz freudenreich e...,"dem wunderschönen bräutgam mein,"
53,E000036,"dem wunderschönen bräutgam mein,","daß ich möge mit jesulein,",jn steter liebe wallen.
54,E000036,jn steter liebe wallen.,"dem wunderschönen bräutgam mein,","singet, springet, jubiliret, triumphiret,"
55,E000036,"singet, springet, jubiliret, triumphiret,",jn steter liebe wallen.,"danckt dem herren, groß ist der könig der ehren!"
56,E000036,"danckt dem herren, groß ist der könig der ehren!","singet, springet, jubiliret, triumphiret,",und denn auch:
57,E000036,"singet, springet, jubiliret, triumphiret,",und die christliche kirche ihm nachsinget:,"danckt dem herren, groß ist der könig der ehren."
58,E000036,"danckt dem herren, groß ist der könig der ehren.","singet, springet, jubiliret, triumphiret,",s videsis dauderst. lab.

In [15]:
def get_closest_verse(sermon_line: str, source: list) -> list:
    best_match = ""
    best_score = 0
    for verse in source:
        sim_score = fuzz.ratio(sermon_line, verse.lower())
        if sim_score > best_score:
            best_score = sim_score
            best_match = verse
    
    return [best_match, best_score, source.index(best_match)]

In [16]:
results[["best_match", "sim_score", "line"]] = results["verse"].apply(lambda x: pd.Series(get_closest_verse(x, liedtext_morgenstern)))

In [17]:
results

,sermon,verse,text_before,text_after,best_match,sim_score,line
0,E000091,ey/ mein perle du werthe cron/,was ich gesucht bin ich gewehrt.,wahr gottes und marien sohn/,Ey mein Perle / du werthe Kron /,90.322581,9
1,E000091,wahr gottes und marien sohn/,ey/ mein perle du werthe cron/,ein hochgeborner könig/ mein hertz heisst dich...,Wahr Gottes vnd Marien Sohn /,94.736842,10
2,E000091,ein hochgeborner könig/ mein hertz heisst dich...,wahr gottes und marien sohn/,dein süsses evangelium/ ist lauter milch und h...,"Mein Hertz heißt dich ein lilium,",68.131868,12
3,E000091,dein süsses evangelium/ ist lauter milch und h...,ein hochgeborner könig/ mein hertz heisst dich...,ey mein/ blümlein/ hosianna/,Jst lauter Milch vnd Honig /,60.759494,14
4,E000091,ey mein/ blümlein/ hosianna/,dein süsses evangelium/ ist lauter milch und h...,himlisch manna/ daß wir essen/,Ey mein Blümlein Hosianna /,94.545455,15
5,E000091,himlisch manna/ daß wir essen/,ey mein/ blümlein/ hosianna/,deiner kan ich nicht vergessen.,Himmlisch Manna Das wir essen /,91.803279,16
6,E000091,deiner kan ich nicht vergessen.,himlisch manna/ daß wir essen/,zwingt die seiten in cythara/,Deiner kan ich nicht vergessen.,100.000000,17
7,E000091,zwingt die seiten in cythara/,deiner kan ich nicht vergessen.,vnd lasst die süsse musica/,Zwingt die Sayten in Cythara.,89.655172,45
8,E000091,vnd lasst die süsse musica/,zwingt die seiten in cythara/,ganz freudenreich erschallen/ daß ich möge mit...,"Vnd laßt die süsse Musica,",90.566038,46
9,E000091,ganz freudenreich erschallen/ daß ich möge mit...,vnd lasst die süsse musica/,den allerhöchsten bräutgam mein/,Gantz frewdenreich erschallen:,62.790698,47
10,E000091,den allerhöchsten bräutgam mein/,ganz freudenreich erschallen/ daß ich möge mit...,jn steter liebe wallen/,Dem wunder schönen Bräutgam mein /,72.727273,49
11,E000091,jn steter liebe wallen/,den allerhöchsten bräutgam mein/,singet/ springet/ jubiliret/ triumphiret/,In stäter Liebe wallen.,86.956522,50
12,E000091,singet/ springet/ jubiliret/ triumphiret/,jn steter liebe wallen/,danckt dem herrn/ groß ist der könig der ehren.,Singet springet Jubilieret triumphieret /,92.682927,51
13,E000091,danckt dem herrn/ groß ist der könig der ehren.,singet/ springet/ jubiliret/ triumphiret/,vnd so viel vom ersten stück/,Danckt dem HERREN Groß ist der König der Ehren.,97.872340,52
14,E000083,zwingt die saiten in cythara/,2. wem es vorgespielet worden?,und lasst die süsse musica gantz freudenreich ...,Zwingt die Sayten in Cythara.,93.103448,45
15,E000083,und lasst die süsse musica gantz freudenreich ...,zwingt die saiten in cythara/,singet/ springet/ jubiliret/ triumphiret/,Gantz frewdenreich erschallen:,64.367816,47
16,E000083,singet/ springet/ jubiliret/ triumphiret/,und lasst die süsse musica gantz freudenreich ...,danckt dem herren/ groß ist der könig der ehren/,Singet springet Jubilieret triumphieret /,92.682927,51
17,E000083,danckt dem herren/ groß ist der könig der ehren/,singet/ springet/ jubiliret/ triumphiret/,amen.,Danckt dem HERREN Groß ist der König der Ehren.,96.842105,52
18,E000083,amen.,danckt dem herren/ groß ist der könig der ehren/,frolocket mit händen alle völcker/,Die Flamme deiner Liebe.,34.482759,20
19,E000079,zwingt die säiten in cithara/,sollen wir doch dem herrn singen und spielen i...,und last die süsse musica/,Zwingt die Sayten in Cythara.,86.206897,45
20,E000079,und last die süsse musica/,zwingt die säiten in cithara/,gantz freudenreich erschallen. müssen wir scho...,"Vnd laßt die süsse Musica,",88.461538,46
21,E000079,gantz freudenreich erschallen. müssen wir scho...,und last die süsse musica/,oder die harpfen an die weide hengen/,Gantz frewdenreich erschallen:,46.666667,47
22,E000075,so zwingt demnach die saiten in cithara/,sonst ist all euer gottesdienst eitel und gieb...,und laßt die süße musica gantz freudenreich er...,Zwingt die Sayten in Cythara.,75.362319,45
23,E000075,und laßt die süße musica gantz freudenreich er...,so zwingt demnach die saiten in cithara/,singet/ klinget/ jubiliret/ triumphiret/,Gantz frewdenreich erschallen:,65.882353,47
24,E000075,singet/ klinget/ jubiliret/ triumphiret/,und laßt die süße musica gantz freudenreich er...,danckt dem herren/ groß ist der könig der ehren!,Singet springet Jubilieret triumphieret /,86.419753,51
25,E000075,danckt dem herren/ groß ist der könig der ehren!,singet/ klinget/ jubiliret/ triumphiret/,dir aber/ o du vater des liechts/,Danckt dem HERREN Groß ist der König der Ehren.,96.842105,52
26,E000072,zwingt die saiten in cithara/,43/32. und die christliche kirche redet dort i...,und last die süße musica gantz n b freudenreic...,Zwingt die Sayten in Cythara.,89.655172,45
27,E000072,und last die süße musica gantz n b freudenreic...,zwingt die saiten in cithara/,so wird adam auff dem felde/,Gantz frewdenreich erschallen:,62.921348,47
28,E000070,"so zwingt die säiten in cithara,",amen. demnach,und lasst die süsse musica gantz freudenreich ...,Zwingt die Sayten in Cythara.,81.967213,45
29,E000070,und lasst die süsse musica gantz freudenreich ...,"so zwingt die säiten in cithara,",singet/ klinget/ jubiliret/ triumphiret/,Gantz frewdenreich erschallen:,64.367816,47
30,E000070,singet/ klinget/ jubiliret/ triumphiret/,und lasst die süsse musica gantz freudenreich ...,danckt dem herren/ groß ist der könig der ehren.,Singet springet Jubilieret triumphieret /,86.419753,51
31,E000070,danckt dem herren/ groß ist der könig der ehren.,singet/ klinget/ jubiliret/ triumphiret/,si vox praeconis clara undique personat alto i...,Danckt dem HERREN Groß ist der König der Ehren.,98.947368,52
32,E000068,"zwingt die seiten in cithara,",nun,zwingt die pfeiffen in organo und lasst die sü...,Zwingt die Sayten in Cythara.,86.206897,45
33,E000068,zwingt die pfeiffen in organo und lasst die sü...,"zwingt die seiten in cithara,",gantz freudenreich erschallen.,"Vnd laßt die süsse Musica,",57.831325,46
34,E000068,gantz freudenreich erschallen.,zwingt die pfeiffen in organo und lasst die sü...,alles/ was odem hat/,Gantz frewdenreich erschallen:,93.333333,47
35,E000056,das eintzige gesäzz: zwingt die saiten in cith...,mit einander werden gesungen und geklungen haben/,der zu unserer orgel-weyhe erwehlte text/,Zwingt die Sayten in Cythara.,65.060241,45
36,E000104,zwingt doch die säyten in cithara/,und mit vollem munde ihn loben!,und last die schöne musica gantz freudenreich ...,Zwingt die Sayten in Cythara.,82.539683,45
37,E000104,und last die schöne musica gantz freudenreich ...,zwingt doch die säyten in cithara/,selbst die seraphinen gehen euch mit ihrem exe...,Gantz frewdenreich erschallen:,64.367816,47
38,E000052,zwingt die säyten in cythara etc.,singet mit einstimmen unserer lobschallenden n...,und bethet darauf ein gläubiges und andächtige...,Zwingt die Sayten in Cythara.,90.322581,45
39,E000052,"zwingt die säyten in cithara,",amabimus &amp; laudabimus wir werden gott lieb...,und last die süsse musica gantz freudenreich e...,Zwingt die Sayten in Cythara.,89.655172,45
40,E000052,und last die süsse musica gantz freudenreich e...,"zwingt die säyten in cithara,",daß ich möge mit jesulein dem allerschönsten b...,Gantz frewdenreich erschallen:,65.116279,47
41,E000052,daß ich möge mit jesulein dem allerschönsten b...,und last die süsse musica gantz freudenreich e...,"nimmermehr kan eine orgel so viel züge haben,",Dem wunder schönen Bräutgam mein /,53.448276,49
42,E000061,herr gott vater mein starcker held etc.,wenn wir noch zuvor zur ermunterung unsrer and...,den 5. 6. und 7.,HERR Gott Vatter / mein starcker Heldt /,88.607595,36
43,E000061,wie schön leuchtet der morgenstern.,v. aus dem liede:,das heutige heilige evangelium am 1.,Wie schön leuchtet der Morgenstern /,95.774648,0
44,E000042,"zwingt die saiten in cythara,","auch einander, also desto freudiger zuruffen.","und lasst die süsse musica,",Zwingt die Sayten in Cythara.,93.103448,45
45,E000042,"und lasst die süsse musica,","zwingt die saiten in cythara,","ganz freudenreich erschallen, daß ich möge mit...","Vnd laßt die süsse Musica,",90.566038,46
46,E000042,"ganz freudenreich erschallen, daß ich möge mit...","und lasst die süsse musica,",jn steter liebe wallen!,Dem wunder schönen Bräutgam mein /,50.819672,49
47,E000042,jn steter liebe wallen!,"ganz freudenreich erschallen, daß ich möge mit...","singet, springet, jubiliret, triumphiret,",In stäter Liebe wallen.,86.956522,50
48,E000042,"singet, springet, jubiliret, triumphiret,",jn steter liebe wallen!,"danckt dem herren, groß ist der könig der ehren.",Singet springet Jubilieret triumphieret /,90.243902,51
49,E000042,"danckt dem herren, groß ist der könig der ehren.","singet, springet, jubiliret, triumphiret,",amen!,Danckt dem HERREN Groß ist der König der Ehren.,98.947368,52
50,E000036,"zwingt die säiten in cithara,",mit eurer angenehmen music uns eine sabbathslu...,und laßt die süsse musica gantz freudenreich e...,Zwingt die Sayten in Cythara.,86.206897,45
51,E000036,und laßt die süsse musica gantz freudenreich e...,"zwingt die säiten in cithara,","daß ich möge mit jesulein,",Gantz frewdenreich erschallen:,65.116279,47
52,E000036,"daß ich möge mit jesulein,",und laßt die süsse musica gantz freudenreich e...,"dem wunderschönen bräutgam mein,",Daß ich möge mit Jesulein /,94.339623,48
53,E000036,"dem wunderschönen bräutgam mein,","daß ich möge mit jesulein,",jn steter liebe wallen.,Dem wunder schönen Bräutgam mein /,93.939394,49
54,E000036,jn steter liebe wallen.,"dem wunderschönen bräutgam mein,","singet, springet, jubiliret, triumphiret,",In stäter Liebe wallen.,91.304348,50
55,E000036,"singet, springet, jubiliret, triumphiret,",jn steter liebe wallen.,"danckt dem herren, groß ist der könig der ehren!",Singet springet Jubilieret triumphieret /,90.243902,51
56,E000036,"danckt dem herren, groß ist der könig der ehren!","singet, springet, jubiliret, triumphiret,",und denn auch:,Danckt dem HERREN Groß ist der König der Ehren.,96.842105,52
57,E000036,"singet, springet, jubiliret, triumphiret,",und die christliche kirche ihm nachsinget:,"danckt dem herren, groß ist der könig der ehren.",Singet springet Jubilieret triumphieret /,90.243902,51
58,E000036,"danckt dem herren, groß ist der könig der ehren.","singet, springet, jubiliret, triumphiret,",s videsis dauderst. lab.,Danckt dem HERREN Groß ist der König der Ehren.,98.947368,52

In [18]:
quoting_sermons = results['sermon'].values.tolist()

In [19]:
x = results.loc[results["best_match"] == "Singet springet Jubilieret triumphieret /"].values.tolist()[0]

In [21]:
lines_with_data = []
for line in liedtext_morgenstern:
    row_list = results.loc[results["best_match"] == line].values.tolist()
    lines_with_data.append({"name": line, "value":row_list})

lines_with_data

[{'name': 'Wie schön leuchtet der Morgenstern /',
  'value': [['E000061',
    'wie schön leuchtet der morgenstern.',
    'v. aus dem liede:',
    'das heutige heilige evangelium am 1.',
    'Wie schön leuchtet der Morgenstern /',
    95.77464788732395,
    0]]},
 {'name': 'Voll Gnad vnd Warheit von dem HERRN /', 'value': []},
 {'name': 'Die süsse Wurtzel Jesse?', 'value': []},
 {'name': 'Du Sohn Dauid auß Jacobs Stamm /', 'value': []},
 {'name': 'Mein König vnd mein Bräutigam /', 'value': []},
 {'name': 'Hast mir mein Hertz besessen /', 'value': []},
 {'name': 'Lieblich freundtlich Schön vnd herrlich /', 'value': []},
 {'name': 'Groß vnd ehrlich Reich von Gaben /', 'value': []},
 {'name': 'Hoch vnd sehr prächtig erhaben.', 'value': []},
 {'name': 'Ey mein Perle / du werthe Kron /',
  'value': [['E000091',
    'ey/ mein perle du werthe cron/',
    'was ich gesucht bin ich gewehrt.',
    'wahr gottes und marien sohn/',
    'Ey mein Perle / du werthe Kron /',
    90.32258064516128,
    9]]},
 {'name': 'Wahr Gottes vnd Marien Sohn /',
  'value': [['E000091',
    'wahr gottes und marien sohn/',
    'ey/ mein perle du werthe cron/',
    'ein hochgeborner könig/ mein hertz heisst dich ein lilium/',
    'Wahr Gottes vnd Marien Sohn /',
    94.73684210526316,
    10]]},
 {'name': 'Ein hochgeborner König /', 'value': []},
 {'name': 'Mein Hertz heißt dich ein lilium,',
  'value': [['E000091',
    'ein hochgeborner könig/ mein hertz heisst dich ein lilium/',
    'wahr gottes und marien sohn/',
    'dein süsses evangelium/ ist lauter milch und honig:',
    'Mein Hertz heißt dich ein lilium,',
    68.13186813186813,
    12]]},
 {'name': 'Dein süsses Euangelium,', 'value': []},
 {'name': 'Jst lauter Milch vnd Honig /',
  'value': [['E000091',
    'dein süsses evangelium/ ist lauter milch und honig:',
    'ein hochgeborner könig/ mein hertz heisst dich ein lilium/',
    'ey mein/ blümlein/ hosianna/',
    'Jst lauter Milch vnd Honig /',
    60.75949367088608,
    14]]},
 {'name': 'Ey mein Blümlein Hosianna /',
  'value': [['E000091',
    'ey mein/ blümlein/ hosianna/',
    'dein süsses evangelium/ ist lauter milch und honig:',
    'himlisch manna/ daß wir essen/',
    'Ey mein Blümlein Hosianna /',
    94.54545454545455,
    15]]},
 {'name': 'Himmlisch Manna Das wir essen /',
  'value': [['E000091',
    'himlisch manna/ daß wir essen/',
    'ey mein/ blümlein/ hosianna/',
    'deiner kan ich nicht vergessen.',
    'Himmlisch Manna Das wir essen /',
    91.80327868852459,
    16]]},
 {'name': 'Deiner kan ich nicht vergessen.',
  'value': [['E000091',
    'deiner kan ich nicht vergessen.',
    'himlisch manna/ daß wir essen/',
    'zwingt die seiten in cythara/',
    'Deiner kan ich nicht vergessen.',
    100.0,
    17]]},
 {'name': 'Geuß sehr tieff in mein Hertz hineyn /', 'value': []},
 {'name': 'Du heller Jaspis vnd Rubin /', 'value': []},
 {'name': 'Die Flamme deiner Liebe.',
  'value': [['E000083',
    'amen.',
    'danckt dem herren/ groß ist der könig der ehren/',
    'frolocket mit händen alle völcker/',
    'Die Flamme deiner Liebe.',
    34.48275862068966,
    20]]},
 {'name': 'Vnd erfreuw mich / daß ich doch bleib', 'value': []},
 {'name': 'An deinem außerwehlten Leib', 'value': []},
 {'name': 'Ein lebendige Rippe /', 'value': []},
 {'name': 'Nach dir ist mir /', 'value': []},
 {'name': 'Gratiosa cœli rosa Kranck vnd glümmet', 'value': []},
 {'name': 'Mein Hertz / durch Liebe verwundet.', 'value': []},
 {'name': 'Von Gott kompt mir ein Frewdenschein /', 'value': []},
 {'name': 'Wenn du mit deinen Eugelein /', 'value': []},
 {'name': 'Mich freundtlich thust anblicken /', 'value': []},
 {'name': 'O HERR Jesu mein trawtes Gut /', 'value': []},
 {'name': 'Dein Wort / dein Geist / dein Leib vnd Blut /', 'value': []},
 {'name': 'Mich innerlich erquicken. Nimm mich /', 'value': []},
 {'name': 'freundtlich Jn dein Arme /', 'value': []},
 {'name': 'Daß ich warme Werd von Gnaden /', 'value': []},
 {'name': 'Auff dein Wort komm ich geladen.', 'value': []},
 {'name': 'HERR Gott Vatter / mein starcker Heldt /',
  'value': [['E000061',
    'herr gott vater mein starcker held etc.',
    'wenn wir noch zuvor zur ermunterung unsrer andacht miteinander werden gesungen und angestimmet haben:',
    'den 5. 6. und 7.',
    'HERR Gott Vatter / mein starcker Heldt /',
    88.60759493670886,
    36]]},
 {'name': 'Du hast mich ewig / für der Welt /', 'value': []},
 {'name': 'In deinem Sohn geliebet /', 'value': []},
 {'name': 'Dein Sohn hat mich jhm selbst vertrawt /', 'value': []},
 {'name': 'Er ist mein Schatz / ich bin sein Braut /', 'value': []},
 {'name': 'Sehr hoch in jhm erfreuwet.', 'value': []},
 {'name': 'Eya Eya Himmlisch Leben /', 'value': []},
 {'name': 'wirdt er geben Mir dort oben /', 'value': []},
 {'name': 'Ewig soll mein Hertz jhn loben.', 'value': []},
 {'name': 'Zwingt die Sayten in Cythara.',
  'value': [['E000091',
    'zwingt die seiten in cythara/',
    'deiner kan ich nicht vergessen.',
    'vnd lasst die süsse musica/',
    'Zwingt die Sayten in Cythara.',
    89.65517241379311,
    45],
   ['E000083',
    'zwingt die saiten in cythara/',
    '2. wem es vorgespielet worden?',
    'und lasst die süsse musica gantz freudenreich erschallen.',
    'Zwingt die Sayten in Cythara.',
    93.10344827586206,
    45],
   ['E000079',
    'zwingt die säiten in cithara/',
    'sollen wir doch dem herrn singen und spielen in unsern hertzen.',
    'und last die süsse musica/',
    'Zwingt die Sayten in Cythara.',
    86.20689655172413,
    45],
   ['E000075',
    'so zwingt demnach die saiten in cithara/',
    'sonst ist all euer gottesdienst eitel und giebt einen übellautenden schall für den ohren des großen gottes.',
    'und laßt die süße musica gantz freudenreich erschallen;',
    'Zwingt die Sayten in Cythara.',
    75.36231884057972,
    45],
   ['E000072',
    'zwingt die saiten in cithara/',
    '43/32. und die christliche kirche redet dort ihre gespielinnen an:',
    'und last die süße musica gantz n b freudenreich erschallen.',
    'Zwingt die Sayten in Cythara.',
    89.65517241379311,
    45],
   ['E000070',
    'so zwingt die säiten in cithara,',
    'amen. demnach',
    'und lasst die süsse musica gantz freudenreich erschallen;',
    'Zwingt die Sayten in Cythara.',
    81.9672131147541,
    45],
   ['E000068',
    'zwingt die seiten in cithara,',
    'nun',
    'zwingt die pfeiffen in organo und lasst die süsse musica,',
    'Zwingt die Sayten in Cythara.',
    86.20689655172413,
    45],
   ['E000056',
    'das eintzige gesäzz: zwingt die saiten in cithara etc.',
    'mit einander werden gesungen und geklungen haben/',
    'der zu unserer orgel-weyhe erwehlte text/',
    'Zwingt die Sayten in Cythara.',
    65.06024096385542,
    45],
   ['E000104',
    'zwingt doch die säyten in cithara/',
    'und mit vollem munde ihn loben!',
    'und last die schöne musica gantz freudenreich erschallen!',
    'Zwingt die Sayten in Cythara.',
    82.53968253968253,
    45],
   ['E000052',
    'zwingt die säyten in cythara etc.',
    'singet mit einstimmen unserer lobschallenden neuen orgel:',
    'und bethet darauf ein gläubiges und andächtiges vater unser',
    'Zwingt die Sayten in Cythara.',
    90.32258064516128,
    45],
   ['E000052',
    'zwingt die säyten in cithara,',
    'amabimus &amp; laudabimus wir werden gott lieben und loben und der bekandte kirchengesang führet die liebe jesu als eine würckung der instrumental-musique an:',
    'und last die süsse musica gantz freudenreich erschallen;',
    'Zwingt die Sayten in Cythara.',
    89.65517241379311,
    45],
   ['E000042',
    'zwingt die saiten in cythara,',
    'auch einander, also desto freudiger zuruffen.',
    'und lasst die süsse musica,',
    'Zwingt die Sayten in Cythara.',
    93.10344827586206,
    45],
   ['E000036',
    'zwingt die säiten in cithara,',
    'mit eurer angenehmen music uns eine sabbathslust an dem herrn zu erwecken:',
    'und laßt die süsse musica gantz freudenreich erschallen,',
    'Zwingt die Sayten in Cythara.',
    86.20689655172413,
    45]]},
 {'name': 'Vnd laßt die süsse Musica,',
  'value': [['E000091',
    'vnd lasst die süsse musica/',
    'zwingt die seiten in cythara/',
    'ganz freudenreich erschallen/ daß ich möge mit jesulein/',
    'Vnd laßt die süsse Musica,',
    90.56603773584906,
    46],
   ['E000079',
    'und last die süsse musica/',
    'zwingt die säiten in cithara/',
    'gantz freudenreich erschallen. müssen wir schon manchmal in dieser welt weinen und heulen/',
    'Vnd laßt die süsse Musica,',
    88.46153846153845,
    46],
   ['E000068',
    'zwingt die pfeiffen in organo und lasst die süsse musica,',
    'zwingt die seiten in cithara,',
    'gantz freudenreich erschallen.',
    'Vnd laßt die süsse Musica,',
    57.831325301204814,
    46],
   ['E000042',
    'und lasst die süsse musica,',
    'zwingt die saiten in cythara,',
    'ganz freudenreich erschallen, daß ich möge mit jesulein dem wunderschönen bräutgam mein,',
    'Vnd laßt die süsse Musica,',
    90.56603773584906,
    46]]},
 {'name': 'Gantz frewdenreich erschallen:',
  'value': [['E000091',
    'ganz freudenreich erschallen/ daß ich möge mit jesulein/',
    'vnd lasst die süsse musica/',
    'den allerhöchsten bräutgam mein/',
    'Gantz frewdenreich erschallen:',
    62.7906976744186,
    47],
   ['E000083',
    'und lasst die süsse musica gantz freudenreich erschallen.',
    'zwingt die saiten in cythara/',
    'singet/ springet/ jubiliret/ triumphiret/',
    'Gantz frewdenreich erschallen:',
    64.36781609195403,
    47],
   ['E000079',
    'gantz freudenreich erschallen. müssen wir schon manchmal in dieser welt weinen und heulen/',
    'und last die süsse musica/',
    'oder die harpfen an die weide hengen/',
    'Gantz frewdenreich erschallen:',
    46.666666666666664,
    47],
   ['E000075',
    'und laßt die süße musica gantz freudenreich erschallen;',
    'so zwingt demnach die saiten in cithara/',
    'singet/ klinget/ jubiliret/ triumphiret/',
    'Gantz frewdenreich erschallen:',
    65.88235294117646,
    47],
   ['E000072',
    'und last die süße musica gantz n b freudenreich erschallen.',
    'zwingt die saiten in cithara/',
    'so wird adam auff dem felde/',
    'Gantz frewdenreich erschallen:',
    62.92134831460674,
    47],
   ['E000070',
    'und lasst die süsse musica gantz freudenreich erschallen;',
    'so zwingt die säiten in cithara,',
    'singet/ klinget/ jubiliret/ triumphiret/',
    'Gantz frewdenreich erschallen:',
    64.36781609195403,
    47],
   ['E000068',
    'gantz freudenreich erschallen.',
    'zwingt die pfeiffen in organo und lasst die süsse musica,',
    'alles/ was odem hat/',
    'Gantz frewdenreich erschallen:',
    93.33333333333333,
    47],
   ['E000104',
    'und last die schöne musica gantz freudenreich erschallen!',
    'zwingt doch die säyten in cithara/',
    'selbst die seraphinen gehen euch mit ihrem exempel vor/',
    'Gantz frewdenreich erschallen:',
    64.36781609195403,
    47],
   ['E000052',
    'und last die süsse musica gantz freudenreich erschallen;',
    'zwingt die säyten in cithara,',
    'daß ich möge mit jesulein dem allerschönsten bräutgam mein in steter liebe wallen.',
    'Gantz frewdenreich erschallen:',
    65.11627906976744,
    47],
   ['E000036',
    'und laßt die süsse musica gantz freudenreich erschallen,',
    'zwingt die säiten in cithara,',
    'daß ich möge mit jesulein,',
    'Gantz frewdenreich erschallen:',
    65.11627906976744,
    47]]},
 {'name': 'Daß ich möge mit Jesulein /',
  'value': [['E000036',
    'daß ich möge mit jesulein,',
    'und laßt die süsse musica gantz freudenreich erschallen,',
    'dem wunderschönen bräutgam mein,',
    'Daß ich möge mit Jesulein /',
    94.33962264150944,
    48]]},
 {'name': 'Dem wunder schönen Bräutgam mein /',
  'value': [['E000091',
    'den allerhöchsten bräutgam mein/',
    'ganz freudenreich erschallen/ daß ich möge mit jesulein/',
    'jn steter liebe wallen/',
    'Dem wunder schönen Bräutgam mein /',
    72.72727272727273,
    49],
   ['E000052',
    'daß ich möge mit jesulein dem allerschönsten bräutgam mein in steter liebe wallen.',
    'und last die süsse musica gantz freudenreich erschallen;',
    'nimmermehr kan eine orgel so viel züge haben,',
    'Dem wunder schönen Bräutgam mein /',
    53.448275862068975,
    49],
   ['E000042',
    'ganz freudenreich erschallen, daß ich möge mit jesulein dem wunderschönen bräutgam mein,',
    'und lasst die süsse musica,',
    'jn steter liebe wallen!',
    'Dem wunder schönen Bräutgam mein /',
    50.81967213114754,
    49],
   ['E000036',
    'dem wunderschönen bräutgam mein,',
    'daß ich möge mit jesulein,',
    'jn steter liebe wallen.',
    'Dem wunder schönen Bräutgam mein /',
    93.93939393939394,
    49]]},
 {'name': 'In stäter Liebe wallen.',
  'value': [['E000091',
    'jn steter liebe wallen/',
    'den allerhöchsten bräutgam mein/',
    'singet/ springet/ jubiliret/ triumphiret/',
    'In stäter Liebe wallen.',
    86.95652173913044,
    50],
   ['E000042',
    'jn steter liebe wallen!',
    'ganz freudenreich erschallen, daß ich möge mit jesulein dem wunderschönen bräutgam mein,',
    'singet, springet, jubiliret, triumphiret,',
    'In stäter Liebe wallen.',
    86.95652173913044,
    50],
   ['E000036',
    'jn steter liebe wallen.',
    'dem wunderschönen bräutgam mein,',
    'singet, springet, jubiliret, triumphiret,',
    'In stäter Liebe wallen.',
    91.30434782608697,
    50]]},
 {'name': 'Singet springet Jubilieret triumphieret /',
  'value': [['E000091',
    'singet/ springet/ jubiliret/ triumphiret/',
    'jn steter liebe wallen/',
    'danckt dem herrn/ groß ist der könig der ehren.',
    'Singet springet Jubilieret triumphieret /',
    92.6829268292683,
    51],
   ['E000083',
    'singet/ springet/ jubiliret/ triumphiret/',
    'und lasst die süsse musica gantz freudenreich erschallen.',
    'danckt dem herren/ groß ist der könig der ehren/',
    'Singet springet Jubilieret triumphieret /',
    92.6829268292683,
    51],
   ['E000075',
    'singet/ klinget/ jubiliret/ triumphiret/',
    'und laßt die süße musica gantz freudenreich erschallen;',
    'danckt dem herren/ groß ist der könig der ehren!',
    'Singet springet Jubilieret triumphieret /',
    86.41975308641976,
    51],
   ['E000070',
    'singet/ klinget/ jubiliret/ triumphiret/',
    'und lasst die süsse musica gantz freudenreich erschallen;',
    'danckt dem herren/ groß ist der könig der ehren.',
    'Singet springet Jubilieret triumphieret /',
    86.41975308641976,
    51],
   ['E000042',
    'singet, springet, jubiliret, triumphiret,',
    'jn steter liebe wallen!',
    'danckt dem herren, groß ist der könig der ehren.',
    'Singet springet Jubilieret triumphieret /',
    90.2439024390244,
    51],
   ['E000036',
    'singet, springet, jubiliret, triumphiret,',
    'jn steter liebe wallen.',
    'danckt dem herren, groß ist der könig der ehren!',
    'Singet springet Jubilieret triumphieret /',
    90.2439024390244,
    51],
   ['E000036',
    'singet, springet, jubiliret, triumphiret,',
    'und die christliche kirche ihm nachsinget:',
    'danckt dem herren, groß ist der könig der ehren.',
    'Singet springet Jubilieret triumphieret /',
    90.2439024390244,
    51]]},
 {'name': 'Danckt dem HERREN Groß ist der König der Ehren.',
  'value': [['E000091',
    'danckt dem herrn/ groß ist der könig der ehren.',
    'singet/ springet/ jubiliret/ triumphiret/',
    'vnd so viel vom ersten stück/',
    'Danckt dem HERREN Groß ist der König der Ehren.',
    97.87234042553192,
    52],
   ['E000083',
    'danckt dem herren/ groß ist der könig der ehren/',
    'singet/ springet/ jubiliret/ triumphiret/',
    'amen.',
    'Danckt dem HERREN Groß ist der König der Ehren.',
    96.84210526315789,
    52],
   ['E000075',
    'danckt dem herren/ groß ist der könig der ehren!',
    'singet/ klinget/ jubiliret/ triumphiret/',
    'dir aber/ o du vater des liechts/',
    'Danckt dem HERREN Groß ist der König der Ehren.',
    96.84210526315789,
    52],
   ['E000070',
    'danckt dem herren/ groß ist der könig der ehren.',
    'singet/ klinget/ jubiliret/ triumphiret/',
    'si vox praeconis clara undique personat alto in templo,',
    'Danckt dem HERREN Groß ist der König der Ehren.',
    98.94736842105263,
    52],
   ['E000042',
    'danckt dem herren, groß ist der könig der ehren.',
    'singet, springet, jubiliret, triumphiret,',
    'amen!',
    'Danckt dem HERREN Groß ist der König der Ehren.',
    98.94736842105263,
    52],
   ['E000036',
    'danckt dem herren, groß ist der könig der ehren!',
    'singet, springet, jubiliret, triumphiret,',
    'und denn auch:',
    'Danckt dem HERREN Groß ist der König der Ehren.',
    96.84210526315789,
    52],
   ['E000036',
    'danckt dem herren, groß ist der könig der ehren.',
    'singet, springet, jubiliret, triumphiret,',
    's videsis dauderst. lab.',
    'Danckt dem HERREN Groß ist der König der Ehren.',
    98.94736842105263,
    52]]},
 {'name': 'Wie bin ich doch so hertzlich fro /', 'value': []},
 {'name': 'Daß mein Schatz ist das A vnd O /', 'value': []},
 {'name': 'Der Anfang / vnd das Ende:', 'value': []},
 {'name': 'Er wirdt mich doch zu seinem Preyß /', 'value': []},
 {'name': 'Auffnemmen in das Paradeiß /', 'value': []},
 {'name': 'Deß klopff ich in die Hände.', 'value': []},
 {'name': 'Amen Amen Komm du schone', 'value': []},
 {'name': 'FrewdenKrone Bleib du nicht lange /', 'value': []},
 {'name': 'Deiner wart ich mit Verlangen.', 'value': []}]

In [23]:
# when do quote types spike?

sermon = Sermon("E000036")

In [62]:
def year_helper(year):
    year_finder = re.compile(r'[0-9]{4}')
    year_cleaned = re.findall(year_finder, year)[0]
    return int(year_cleaned)

In [101]:
quotes_per_year = []
sermons_per_year = []
for id in ids:
    sermon_quotes = 0
    source_quotes = 0
    song_quotes = 0

    sermon = Sermon(id)

    year = year_helper(sermon.erscheinungsjahr)
    link = f'<a href="https://orgelpredigt.ur.de/{id}" target="_blank">{sermon.kurztitel}</a>'
    sermons_per_year.append([year, sermon.kurztitel, link])

    all_quotes = set(sermon.all_references)
    for quote in all_quotes:
        if quote.startswith("E00"):
            sermon_quotes += 1
        elif quote.startswith("E08") or quote.startswith("E09"):
            source_quotes += 1
        elif quote.startswith("E10"):
            song_quotes += 1
    quotes_per_year.append([year, [sermon_quotes, source_quotes, song_quotes]])

In [103]:
quotes_per_year

[[1602, [0, 7, 0]],
 [1605, [0, 1, 0]],
 [1606, [0, 8, 5]],
 [1610, [0, 3, 1]],
 [1621, [0, 13, 1]],
 [1624, [0, 23, 0]],
 [1628, [0, 6, 1]],
 [1647, [1, 20, 8]],
 [1648, [2, 11, 8]],
 [1651, [1, 24, 7]],
 [1652, [2, 15, 5]],
 [1660, [1, 10, 1]],
 [1664, [0, 7, 4]],
 [1666, [0, 11, 3]],
 [1667, [0, 10, 8]],
 [1671, [0, 15, 4]],
 [1672, [0, 5, 12]],
 [1673, [3, 10, 4]],
 [1675, [3, 6, 5]],
 [1676, [2, 12, 13]],
 [1676, [0, 14, 8]],
 [1680, [3, 10, 7]],
 [1681, [0, 15, 18]],
 [1683, [1, 10, 16]],
 [1685, [2, 12, 1]],
 [1686, [0, 32, 7]],
 [1687, [1, 45, 1]],
 [1689, [0, 24, 1]],
 [1695, [1, 23, 3]],
 [1696, [1, 10, 0]],
 [1700, [0, 13, 10]],
 [1704, [0, 28, 3]],
 [1704, [2, 49, 3]],
 [1709, [1, 7, 1]],
 [1709, [0, 15, 5]],
 [1711, [2, 49, 15]],
 [1711, [0, 15, 2]],
 [1720, [2, 104, 5]],
 [1721, [0, 13, 0]],
 [1721, [3, 12, 11]],
 [1721, [2, 1, 1]],
 [1726, [0, 4, 5]],
 [1727, [0, 8, 6]],
 [1728, [0, 157, 8]],
 [1730, [0, 5, 6]],
 [1735, [0, 11, 17]],
 [1737, [0, 1, 6]],
 [1739, [2, 20, 3]],
 [1740, [0, 1, 3]],
 [1747, [0, 5, 9]],
 [1749, [1, 34, 25]],
 [1749, [0, 1, 2]],
 [1751, [0, 0, 0]],
 [1753, [0, 1, 1]],
 [1761, [1, 34, 7]],
 [1765, [0, 7, 3]],
 [1766, [0, 0, 1]],
 [1767, [0, 0, 3]],
 [1770, [0, 0, 2]],
 [1778, [0, 0, 0]],
 [1781, [0, 0, 0]],
 [1781, [0, 0, 6]],
 [1795, [0, 0, 0]],
 [1797, [0, 0, 1]],
 [1798, [0, 0, 3]]]

In [93]:
sermons_per_year

[[1602,
  'Christliche Predigt (Tübingen 1602)',
  '<a href="https://orgelpredigt.ur.de/E000001" target="_blank">Christliche Predigt (Tübingen 1602)</a>'],
 [1605,
  'Musica instrumentalis (Meißen 1605)',
  '<a href="https://orgelpredigt.ur.de/E000002" target="_blank">Musica instrumentalis (Meißen 1605)</a>'],
 [1606,
  'Christliche Predigt (Tübingen 1606)',
  '<a href="https://orgelpredigt.ur.de/E000029" target="_blank">Christliche Predigt (Tübingen 1606)</a>'],
 [1610,
  'Elogium Organi Musici (Altenburg 1610)',
  '<a href="https://orgelpredigt.ur.de/E000030" target="_blank">Elogium Organi Musici (Altenburg 1610)</a>'],
 [1621,
  'Corona Templi (Nürnberg 1621)',
  '<a href="https://orgelpredigt.ur.de/E000099" target="_blank">Corona Templi (Nürnberg 1621)</a>'],
 [1624,
  'Vlmische Orgel Predigt (Ulm 1624)',
  '<a href="https://orgelpredigt.ur.de/E000003" target="_blank">Vlmische Orgel Predigt (Ulm 1624)</a>'],
 [1628,
  'Musica ecclesiastica (Stettin 1628)',
  '<a href="https://orgelpredigt.ur.de/E000098" target="_blank">Musica ecclesiastica (Stettin 1628)</a>'],
 [1647,
  'Kostbare Bosische Orgel (Zwickau 1647)',
  '<a href="https://orgelpredigt.ur.de/E000096" target="_blank">Kostbare Bosische Orgel (Zwickau 1647)</a>'],
 [1648,
  'Längst=gewüntzschte Mittweidische Orgel=Freude (Dresden 1648)',
  '<a href="https://orgelpredigt.ur.de/E000095" target="_blank">Längst=gewüntzschte Mittweidische Orgel=Freude (Dresden 1648)</a>'],
 [1651,
  'Organologismos (Dresden 1651)',
  '<a href="https://orgelpredigt.ur.de/E000092" target="_blank">Organologismos (Dresden 1651)</a>'],
 [1652,
  'Stolpenische Ehren-Crone (Dresden 1652)',
  '<a href="https://orgelpredigt.ur.de/E000091" target="_blank">Stolpenische Ehren-Crone (Dresden 1652)</a>'],
 [1660,
  'Organolustria Evangelico-Stambachiana (Hof 1660)',
  '<a href="https://orgelpredigt.ur.de/E000090" target="_blank">Organolustria Evangelico-Stambachiana (Hof 1660)</a>'],
 [1664,
  'Encoenia HierOrganica (Halle 1664)',
  '<a href="https://orgelpredigt.ur.de/E000089" target="_blank">Encoenia HierOrganica (Halle 1664)</a>'],
 [1666,
  'Orgel=Predigt (Arnstadt 1666)',
  '<a href="https://orgelpredigt.ur.de/E000086" target="_blank">Orgel=Predigt (Arnstadt 1666)</a>'],
 [1667,
  'Das fröliche Hallelujah (Halle 1667)',
  '<a href="https://orgelpredigt.ur.de/E000085" target="_blank">Das fröliche Hallelujah (Halle 1667)</a>'],
 [1671,
  'Das Gott=Lob=Schallende Hosianna (Leipzig 1671)',
  '<a href="https://orgelpredigt.ur.de/E000083" target="_blank">Das Gott=Lob=Schallende Hosianna (Leipzig 1671)</a>'],
 [1672,
  'Geistliches Orgelwerk (Erfurt 1672)',
  '<a href="https://orgelpredigt.ur.de/E000082" target="_blank">Geistliches Orgelwerk (Erfurt 1672)</a>'],
 [1673,
  'Denck- und Danck-Säule (Rothenburg ob der Tauber [1673])',
  '<a href="https://orgelpredigt.ur.de/E000079" target="_blank">Denck- und Danck-Säule (Rothenburg ob der Tauber [1673])</a>'],
 [1675,
  'Das fröliche Halleluja (Wittenberg 1675)',
  '<a href="https://orgelpredigt.ur.de/E000078" target="_blank">Das fröliche Halleluja (Wittenberg 1675)</a>'],
 [1676,
  'Das Lieblich=klingende Orgeln und Saiten=Spiel (Coburg 1676)',
  '<a href="https://orgelpredigt.ur.de/E000075" target="_blank">Das Lieblich=klingende Orgeln und Saiten=Spiel (Coburg 1676)</a>'],
 [1676,
  'Die andere Predigt (Coburg 1676)',
  '<a href="https://orgelpredigt.ur.de/E000106" target="_blank">Die andere Predigt (Coburg 1676)</a>'],
 [1680,
  'Geistlich= und Gott wohlgefälliges Lob- und Danck-Opffer (Bayreuth 1680)',
  '<a href="https://orgelpredigt.ur.de/E000073" target="_blank">Geistlich= und Gott wohlgefälliges Lob- und Danck-Opffer (Bayreuth 1680)</a>'],
 [1681,
  'Gott und Gnug (Meißen 1681)',
  '<a href="https://orgelpredigt.ur.de/E000072" target="_blank">Gott und Gnug (Meißen 1681)</a>'],
 [1683,
  'Cithara Theologica (Schleusingen 1683)',
  '<a href="https://orgelpredigt.ur.de/E000070" target="_blank">Cithara Theologica (Schleusingen 1683)</a>'],
 [1685,
  'Organi Laudes (Plauen 1685)',
  '<a href="https://orgelpredigt.ur.de/E000108" target="_blank">Organi Laudes (Plauen 1685)</a>'],
 [1686,
  'Organum Mysticum (Dresden 1686)',
  '<a href="https://orgelpredigt.ur.de/E000069" target="_blank">Organum Mysticum (Dresden 1686)</a>'],
 [1687,
  'Das dem Allmächtigen abzustattende Lob (Altenburg s.a.)',
  '<a href="https://orgelpredigt.ur.de/E000068" target="_blank">Das dem Allmächtigen abzustattende Lob (Altenburg s.a.)</a>'],
 [1689,
  'Organo-Praxis Mystica (Görlitz 1689)',
  '<a href="https://orgelpredigt.ur.de/E000067" target="_blank">Organo-Praxis Mystica (Görlitz 1689)</a>'],
 [1695,
  'Eine Christliche Orgel=Predigt (Danzig 1695)',
  '<a href="https://orgelpredigt.ur.de/E000065" target="_blank">Eine Christliche Orgel=Predigt (Danzig 1695)</a>'],
 [1696,
  'Schuldiges Lob Gottes (Nürnberg 1696)',
  '<a href="https://orgelpredigt.ur.de/E000063" target="_blank">Schuldiges Lob Gottes (Nürnberg 1696)</a>'],
 [1700,
  'Die Christliche Harmonie (Jena 1700)',
  '<a href="https://orgelpredigt.ur.de/E000060" target="_blank">Die Christliche Harmonie (Jena 1700)</a>'],
 [1704,
  'Christliche Orgel-Predigt (Danzig s.a.)',
  '<a href="https://orgelpredigt.ur.de/E000058" target="_blank">Christliche Orgel-Predigt (Danzig s.a.)</a>'],
 [1704,
  'Einweihungs-Predigt (Görlitz 1704)',
  '<a href="https://orgelpredigt.ur.de/E000059" target="_blank">Einweihungs-Predigt (Görlitz 1704)</a>'],
 [1709,
  'Orgel Weih-Predigt (Ansbach 1709)',
  '<a href="https://orgelpredigt.ur.de/E000056" target="_blank">Orgel Weih-Predigt (Ansbach 1709)</a>'],
 [1709,
  'Das rein-gestimmte Orgel-Werk unsers Herzens (Nürnberg s.a.)',
  '<a href="https://orgelpredigt.ur.de/E000057" target="_blank">Das rein-gestimmte Orgel-Werk unsers Herzens (Nürnberg s.a.)</a>'],
 [1711,
  'Davids Vermahnung (Dresden 1711)',
  '<a href="https://orgelpredigt.ur.de/E000055" target="_blank">Davids Vermahnung (Dresden 1711)</a>'],
 [1711,
  'Evangelischer Christen Gott-gefällige Kirch-Weyhung (Dresden 1711)',
  '<a href="https://orgelpredigt.ur.de/E000104" target="_blank">Evangelischer Christen Gott-gefällige Kirch-Weyhung (Dresden 1711)</a>'],
 [1720,
  'Vivum Dei Organum (Schneeberg s.a.)',
  '<a href="https://orgelpredigt.ur.de/E000053" target="_blank">Vivum Dei Organum (Schneeberg s.a.)</a>'],
 [1721,
  'Die Kneiphöffsche laute Orgel=Stimme (Königsberg 1721)',
  '<a href="https://orgelpredigt.ur.de/E000051" target="_blank">Die Kneiphöffsche laute Orgel=Stimme (Königsberg 1721)</a>'],
 [1721,
  'Ein wolgerührtes Orgel=Werck (Königsberg 1721)',
  '<a href="https://orgelpredigt.ur.de/E000052" target="_blank">Ein wolgerührtes Orgel=Werck (Königsberg 1721)</a>'],
 [1721,
  'Glaubiger Kinder Gottes Gott=gefällige Music (Augsburg 1721)',
  '<a href="https://orgelpredigt.ur.de/E000074" target="_blank">Glaubiger Kinder Gottes Gott=gefällige Music (Augsburg 1721)</a>'],
 [1726,
  'Die verstimmte Zwölff Grösseste Pfeiffen (Tübingen s.a.)',
  '<a href="https://orgelpredigt.ur.de/E000048" target="_blank">Die verstimmte Zwölff Grösseste Pfeiffen (Tübingen s.a.)</a>'],
 [1727,
  'Die edle und wohlgeordnete Music der Gläubigen (Halle 1727)',
  '<a href="https://orgelpredigt.ur.de/E000046" target="_blank">Die edle und wohlgeordnete Music der Gläubigen (Halle 1727)</a>'],
 [1728,
  'Hymnosophia sacra (Billwerder 1728)',
  '<a href="https://orgelpredigt.ur.de/E000045" target="_blank">Hymnosophia sacra (Billwerder 1728)</a>'],
 [1730,
  'Einweihungs-Predigt (Berlin 1730)',
  '<a href="https://orgelpredigt.ur.de/E000061" target="_blank">Einweihungs-Predigt (Berlin 1730)</a>'],
 [1735,
  'Das Neue Lied (Freiberg 1735)',
  '<a href="https://orgelpredigt.ur.de/E000042" target="_blank">Das Neue Lied (Freiberg 1735)</a>'],
 [1737,
  'Stimme des Predigers (1737)',
  '<a href="https://orgelpredigt.ur.de/E000109" target="_blank">Stimme des Predigers (1737)</a>'],
 [1739,
  'Die Billige Orgel-Freude (Danzig 1739)',
  '<a href="https://orgelpredigt.ur.de/E000041" target="_blank">Die Billige Orgel-Freude (Danzig 1739)</a>'],
 [1740,
  'Winnedisches Reminiscere (Stuttgart 1740)',
  '<a href="https://orgelpredigt.ur.de/E000039" target="_blank">Winnedisches Reminiscere (Stuttgart 1740)</a>'],
 [1747,
  'Den rechtmäßigen Gebrauch der Music (Königsberg 1747)',
  '<a href="https://orgelpredigt.ur.de/E000038" target="_blank">Den rechtmäßigen Gebrauch der Music (Königsberg 1747)</a>'],
 [1749,
  'Die heilige Sabbaths-Lust an dem Herrn (Danzig 1749)',
  '<a href="https://orgelpredigt.ur.de/E000036" target="_blank">Die heilige Sabbaths-Lust an dem Herrn (Danzig 1749)</a>'],
 [1749,
  'Christliche Predigt (Straßburg 1749)',
  '<a href="https://orgelpredigt.ur.de/E000037" target="_blank">Christliche Predigt (Straßburg 1749)</a>'],
 [1751,
  'Musicalische Orgel= Lob= und Ehren=Predigt (s.l. 1751)',
  '<a href="https://orgelpredigt.ur.de/E000035" target="_blank">Musicalische Orgel= Lob= und Ehren=Predigt (s.l. 1751)</a>'],
 [1753,
  'Lob= und Danck=Predigt (Berlin 1753)',
  '<a href="https://orgelpredigt.ur.de/E000034" target="_blank">Lob= und Danck=Predigt (Berlin 1753)</a>'],
 [1761,
  'Der Christen gerechte Freude (Breslau 1761)',
  '<a href="https://orgelpredigt.ur.de/E000027" target="_blank">Der Christen gerechte Freude (Breslau 1761)</a>'],
 [1765,
  'Die heiligen Verrichtungen in dem Hause des Herrn (Eisenach 1765)',
  '<a href="https://orgelpredigt.ur.de/E000024" target="_blank">Die heiligen Verrichtungen in dem Hause des Herrn (Eisenach 1765)</a>'],
 [1766,
  'Der rechte Gebrauch der Orgeln (Altenburg 1766)',
  '<a href="https://orgelpredigt.ur.de/E000023" target="_blank">Der rechte Gebrauch der Orgeln (Altenburg 1766)</a>'],
 [1767,
  'Das heilige und fröliche Aufsehen (Tübingen 1767)',
  '<a href="https://orgelpredigt.ur.de/E000021" target="_blank">Das heilige und fröliche Aufsehen (Tübingen 1767)</a>'],
 [1770,
  'Predigt am Feste der Heimsuchung Mariae (Rostock 1770)',
  '<a href="https://orgelpredigt.ur.de/E000020" target="_blank">Predigt am Feste der Heimsuchung Mariae (Rostock 1770)</a>'],
 [1778,
  'Der Dienst der Orgeln (Jena 1778)',
  '<a href="https://orgelpredigt.ur.de/E000016" target="_blank">Der Dienst der Orgeln (Jena 1778)</a>'],
 [1781,
  'Gast-Predigt (Ulm 1781)',
  '<a href="https://orgelpredigt.ur.de/E000014" target="_blank">Gast-Predigt (Ulm 1781)</a>'],
 [1781,
  'Rede und Predigt bey Einweihung der neuen Orgel (Stockholm 1781)',
  '<a href="https://orgelpredigt.ur.de/E000015" target="_blank">Rede und Predigt bey Einweihung der neuen Orgel (Stockholm 1781)</a>'],
 [1795,
  'Predigt bey Einweyhung der Orgel (s.l. 1795)',
  '<a href="https://orgelpredigt.ur.de/E000009" target="_blank">Predigt bey Einweyhung der Orgel (s.l. 1795)</a>'],
 [1797,
  'Predigt Bey der Einweihung einer Orgel (Leipzig 1797)',
  '<a href="https://orgelpredigt.ur.de/E000008" target="_blank">Predigt Bey der Einweihung einer Orgel (Leipzig 1797)</a>'],
 [1798,
  'Predigt bey der feyerlichen Einweihung der neuen Orgel (Magdeburg 1798)',
  '<a href="https://orgelpredigt.ur.de/E000007" target="_blank">Predigt bey der feyerlichen Einweihung der neuen Orgel (Magdeburg 1798)</a>']]

In [94]:
colors = {
    'Orgelpredigten': 'rgb(135, 44, 162)',
    'Musikwerke': 'rgb(192, 54, 157)',
    'Literatur': 'rgb(234, 79, 136)'
}

In [95]:
df = pd.DataFrame(sermons_per_year, columns=["year", "title", "id"])
# Create full year range
all_years = pd.DataFrame({"year": range(1600,1801)})

# Merge to ensure every year appears, fill missing with 0
df_full = pd.merge(all_years, df, on="year", how="left").fillna(0)

agg = df.groupby("year").agg({
    "title": lambda x: "<br>".join(x.astype(str)),
    "id": lambda x: ", ".join(x.astype(str)),
    "year": "count"
}).rename(columns={"year": "count"}).reset_index()

In [99]:
fig = px.bar(agg, x='year', y='count',
             hover_data='id',
             color_discrete_sequence=['rgb(135, 44, 162)'])
fig.show()

In [102]:
df = pd.DataFrame(quotes_per_year, columns=["Jahr", "Anzahl"])
df[["Orgelpredigten", "Literatur", "Musikwerke"]] = pd.DataFrame(df["Anzahl"].tolist(), index=df.index)
df = df.drop(columns="Anzahl")

# Melt to long format for plotly express
df_long = df.melt(id_vars="Jahr", value_vars=["Orgelpredigten", "Literatur", "Musikwerke"],
                  var_name="type", value_name="Anzahl")

# Create figure
fig = go.Figure()

# Add line traces with custom colors
for t in df_long["type"].unique():
    subset = df_long[df_long["type"] == t]
    fig.add_trace(
        go.Scatter(
            x=subset["Jahr"],
            y=subset["Anzahl"],
            mode="lines+markers",
            name=t,
            line=dict(color=colors[t], width=2),
            marker=dict(size=8)
        )
    )

# Layout
fig.update_layout(
    title="Zeitliche Verteilung von Zitattypen",
    xaxis_title="Jahr",
    yaxis_title="Anzahl"
)

fig.show()

In [104]:
sermon = Sermon("E000036")

In [122]:
sermon.chunked[0][3]["types"]

['', '', '', '', '', ' bibel', ' bibel']

In [ ]:
t = ["", "", ""]

In [119]:
first_type = ""
for i in t:
    if (len(i) != 0):
        first_type = i
        break
print(first_type)

 .